# Generated by Django 3.1.1 on 2020-09-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='english',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scores',
            name='math',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scores',
            name='science',
            field=models.IntegerField(),
        ),
    ]
