# Generated by Django 3.1.1 on 2020-09-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritegroup',
            name='test',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
