# Generated by Django 3.1.1 on 2020-09-07 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0005_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritegroup',
            name='test',
        ),
    ]
