# Generated by Django 3.1.1 on 2020-09-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0006_remove_favoritegroup_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
